.travis.yml

add travis file to build docker image and push it to dockerhub

---

src/components/HomeHeader.js
src/index.js
src/styles/components/home-header.scss
src/styles/home.scss

Signed-off-by: chandan kumar <chandan.kumar@mayadata.io>

Remove the padding left and right padding in header part

---

src/components/ChartDetails.js
src/components/HomeFilter.js
src/components/HomeHeader.js
src/components/InstallModalContent.js
src/pages/Chart.js
src/styles/components/install-modal-content.scss

- maintainers
Update pop with
- logo
- displayname
- provider
chaos filter text

Add new key charts

---

src/components/HomeHeader.js
src/components/InstallModalContent.js
src/styles/chart.scss
src/styles/components/home-header.scss
src/styles/home.scss

Update hero bg
Update pop content

Update hero and pop content

---

server/charts/kubernetes/network/network.chartserviceversion.v0.1.0.yaml
server/charts/kubernetes/network/network.chartserviceversion.yaml
server/charts/kubernetes/state/state.chartserviceversion.v0.1.0.yaml
server/charts/kubernetes/state/state.chartserviceversion.yaml
server/charts/openebs/network/network.chartserviceversion.v0.1.0.yaml
server/charts/openebs/network/network.chartserviceversion.yaml
server/charts/openebs/state/state.chartserviceversion.v0.1.0.yaml
server/charts/openebs/state/state.chartserviceversion.yaml
src/App.js
src/components/ChartCard.js
src/components/HomeHeader.js
src/pages/Chart.js
src/pages/Home.js
src/pages/Subcharts.js
src/redux/actions.js
src/styles/home.scss

- Add a subcharts page
- Add route /charts/{chartsname}/subcharts/{subchartname}
- Show the popup for install
- Remove unecessary console logs

Make charts view for subcharts

---

public/index.html
server/charts/kubernetes/kubernetes.chartserviceversion.v0.1.0.yaml
server/charts/kubernetes/kubernetes.chartserviceversion.yaml
server/charts/kubernetes/network/network.chartserviceversion.v0.1.0.yaml
server/charts/kubernetes/network/network.chartserviceversion.yaml
server/charts/kubernetes/state/state.chartserviceversion.v0.1.0.yaml
server/charts/kubernetes/state/state.chartserviceversion.yaml
server/charts/openebs/kubernetes.package.yaml
server/charts/openebs/network/network.chartserviceversion.v0.1.0.yaml
server/charts/openebs/network/network.chartserviceversion.yaml
server/charts/openebs/openebs.chartserviceversion.v0.1.0.yaml
server/charts/openebs/openebs.chartserviceversion.yaml
server/charts/openebs/openebs.package.yaml
server/handlers.go
src/App.js
src/components/HomeHeader.js
src/pages/Home.js
src/styles/components/chart-details.scss

Update title of the website
Update Hero section content of the home page
update item to primary chaos charts

Update content website

---

README.md

To make it easier for contributors to get started.
Signed-off-by: dravog7 <dravog77@gmail.com>

(fix): Add installation steps start the charhub server

---

src/styles/home.scss

* Fix mobile view of Generic charts
Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

Fix mobile view of Generic charts (#37)

---

server/charts/generic/experiments.yaml
server/charts/generic/pod-network-loss/experiment.yaml

Signed-off-by: daitya109 <adikid1996@gmail.com>
- in charts/generic/experiments.yaml == changed "%" to "PERCENTAGE"
- in charts/generic/pod-network-loss/experiment.yaml == changed "%" to "PERCENTAGE"
reference issue: https://github.com/litmuschaos/litmus/issues/853

(fix) : changed "%" to PERCENTAGE

---

server/charts/generic/generic.chartserviceversion.yaml

Signed-off-by: Adi <adikid1996@gmail.com>
(typo-fix) <area/charthub> : litmus icon link for charts (#59)

[staging to master]

---

nginx/nginx.conf

fixes: #71
Signed-off-by: Harsh Vardhan <harsh59v@gmail.com>

Add support for caching of UI components

---

server/handlers.go

- Fixed the file path for the hosting in the `handlers.go`
Signed-off-by: daitya109 <adikid1996@gmail.com>

(bug-fix)<area/charthub> : fixed the hosting bug

---

LICENSE
server/controller/handler/chart.go
server/controller/handler/handlers.go
server/controller/logger/logger.go
server/pkg/gitops/gitwork.go
server/routes/router.go
server/routes/routes.go

Add Apache 2.0 LICENSE

---

src/components/ChartDetails.js

- This PR includes icons for platforms and maturity
**Updated Icons -**
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>

Added icons for maturity and platforms in chaos-experiments

---

server/controller/handler/chart.go
src/components/ChartCard.js
src/components/ChartDetails.js
src/styles/components/chart-card.scss

icon indicating infra-level experiments in generic and open-ebs

Add chaos type icon in experiments

---

server/controller/handler/chart.go
src/components/ChartCard.js
src/components/ChartDetails.js
src/styles/components/chart-card.scss

* resolve conversation / git
PR for stating to master
Signed-off-by: ashishjain <ashish.jain@mayadata.io>

Add chaos type icon in experiments (#89)

---

server/pkg/analytics/analytics.go
src/components/ChartDetails.js
src/pages/Chart.js
src/pages/Experiments.js
src/styles/components/chart-card.scss
src/styles/components/chart-details.scss

Signed-off-by: aditya109 <adikid1996@gmail.com>
-  added front-end to accommodate  **`GA-support`**  
- made some css changes to counts on experiment-counts
- made api-request timeout limit to 5 minutes
**Solves**  [1098](https://github.com/litmuschaos/litmus/issues/1098)

(feat)Analytics: Support for cumulative experiment count

---

src/pages/Chart.js

- Removed typo from chart.js file
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>

(Bug):Removed typo from charts.js file

---

src/pages/Experiments.js

Signed-off-by: aditya109 <adikid1996@gmail.com>
Fixes [1096] (https://github.com/litmuschaos/litmus/issues/1096)

Bug-Fix:Back- Button Fix

---

server/pkg/analytics/analytics.go
server/pkg/gitops/gitwork.go
src/pages/Home.js

Signed-off-by: aditya109 <adikid1996@gmail.com>
- refactored the TOTAL EXPERIMENTS RUN counting logic in `Home.js`
- changed the git pulling `TimeInterval` constant

(bug): Counter fix in Charthub Footer

---

server/pkg/analytics/analytics.go
server/pkg/gitops/gitwork.go
src/pages/Home.js

Cherry-picked commits:
- (bug): footer-cumulative counter fix (#102)

[cherry-picked for master] 

---

src/styles/components/home-header.scss

* Added home btn to header
* Placement fix
Signed-off-by: Gavin Foutz <gavinafoutz@gmail.com>

(alpha-r13): Cherry-picked to master 

---

README.md

Signed-off-by: Chandan Kumar <chandan.kr404@gmail.com>
- Add FOSSA  license status badge

(license): Add FOSSA  license status badge

---

README.md

Cherry-picked the below changes:
- (license): Add FOSSA  license status badge (#115)
Signed-off-by: Chandan Kumar <chandan.kr404@gmail.com>

[cherry-pick to master]

---

scripts/start.js
src/App.js
src/common/addMetrics.js
src/common/helpers.js
src/components/ChartCard.js
src/components/ChartDetails.js
src/components/Footer.js
src/components/HomeFilter.js
src/components/HomeHeader.js
src/components/InstallModalContent.js
src/components/VideoModalContent.js
src/index.js
src/index.scss
src/pages/Chart.js
src/pages/Experiments.js
src/pages/Home.js
src/redux/actions.js
src/redux/reducers/charts.js
src/redux/store.js
src/styles/components/chart-details.scss

This commit contains the following changes:
- Refactor the code snippets
- Add support to handle the edge cases if some of the value not present in chaos-charts
Signed-off-by: Chandan Kumar <chandan.kr404@gmail.com>

(refactor): Handle the edge cases and refactor the code

---

server/controller/handler/handlers.go
src/components/ChartCard.js
src/styles/components/chart-card.scss
src/styles/components/home-filter.scss

Add upcoming chart status:
Issue fixed: https://github.com/litmuschaos/litmus/issues/1342

(upcoming): Add the status for upcoming chart

---

src/pages/Home.js

(Footer): Fix the total experiment count

---

server/pkg/gitops/gitwork.go
src/components/ChartCard.js
src/styles/components/chart-card.scss

This commit will do the following changes:
- Take the target branch name of chaos-chart from an environment variable
- Remove the 'coming soon' text

feat(server/UI): Update the changes related to upcoming chart

---

src/pages/Home.js

- (ICON): Set the icon path to the staging of chaos-chart
This is a temporary fix of setting the path to staging

(ICON): Set the icon path to staging of chaos-chart

---

src/pages/Experiments.js

- Fix the video link URL finder

(UI): Fix the video link URL finder

---

.gitignore
server/controller/handler/handlers.go
server/pkg/gitops/gitwork.go
src/components/HomeHeader.js

Cherry-picked changes:
- (fix): Fix the version display issue …
- (fix): Fix the versioning listing and get chart file issue …

[Cherry-picked to master]

---

README.md

- Update the README.md to setup development server

(fix): Update the README.md to setup the development server

---

server/pkg/analytics/analytics.go
src/pages/Home.js

- This commit contains the fix for analytics of opearator count

(Bug): Fix the analytics of operator count

---

src/components/Footer.js

Fix the typo text in footer

---

README.md

The steps to Run server in docker has been removed from REDAME.md

This fixes issue #1485 & #1491 in repo litmuschaos/litmus

---

package-lock.json
src/pages/Experiments.js

Added logic for dynamic selection of video url from JSON response.
Issue: https://github.com/litmuschaos/litmus/issues/1461

Fixed Video URL logic (Issue #1461)

---

package-lock.json
src/pages/Experiments.js

I fixed the display name logic and also created a new utility function that extracts the specific experiment with the given experiment name, as the same code was repeated in multiple places. 
Issue: https://github.com/litmuschaos/litmus/issues/1461

Fixed display name logic Issue #1461

---

app/client/src/components/InstallChaos/index.tsx
app/client/src/pages/ErrorPage/index.tsx
app/client/src/pages/ErrorPage/styles.ts
app/client/src/pages/ExperimentGroupPage/index.tsx
app/client/src/pages/ExperimentGroupPage/styles.ts
app/client/src/pages/ExperimentPage/index.tsx
app/client/src/pages/ExperimentPage/styles.ts
app/client/src/pages/HomePage/index.tsx
app/client/src/pages/HomePage/styles.ts
app/client/src/redux/actions/github.ts

- Fixed footer to the bottom of the Screen
- Fixed Minor Typos as discovered
- Solved the Top Contributor list discrepancy 
- Removed unnecessary console logs

Fixed Footer, Typo fixes, Solved Top Contributor Discrepancy and Removed unnecessary console logs 

---

app/client/src/components/ChartGroups/index.tsx
app/client/src/components/InstallChaos/index.tsx
app/client/src/pages/ErrorPage/index.tsx
app/client/src/pages/ErrorPage/styles.ts
app/client/src/pages/ExperimentGroupPage/index.tsx
app/client/src/pages/ExperimentGroupPage/styles.ts
app/client/src/pages/ExperimentPage/index.tsx
app/client/src/pages/ExperimentPage/styles.ts
app/client/src/pages/HomePage/index.tsx
app/client/src/pages/HomePage/styles.ts
app/client/src/redux/actions/github.ts

Cherrypick from staging

---

README.md
app/client/src/pages/HomePage/index.tsx

Fixes #180 
Signed-off-by: gdsoumya <gdsoumya@gmail.com>

Fixed Issue #180

---

app/client/src/components/Loader/index.tsx
app/client/src/pages/HomePage/index.tsx

Signed-off-by: arkajyotiMukherjee <arkajyoti31@gmail.com>

minor fix in a spelling for the heading text

---

app/client/src/components/Loader/index.tsx
app/client/src/pages/HomePage/index.tsx

Signed-off-by: arkajyotiMukherjee <arkajyoti31@gmail.com>

cherry-picked from staging to master

---

app/client/public/index.html

This will add the information related to google analytics, Which will help to track the page view.

(Analytics): Add google tracking information detail

---

app/client/src/components/Footer/index.tsx

redirecting link of footer to mayadata (#190)

---

.travis.yml
app/client/cypress.json
app/client/cypress/fixtures/example.json
app/client/cypress/integration/CharthubSmallTests.spec.js
app/client/cypress/plugins/index.js
app/client/cypress/support/commands.js
app/client/cypress/support/index.js
app/client/package-lock.json
app/client/package.json
app/client/src/components/BackButton/index.tsx
app/client/src/components/Footer/index.tsx
app/client/src/components/SearchBar/index.tsx

Signed-off-by: Jonsy13 <vedant.shrotria@mayadata.io>

Cypress Integration and Unique Identifiers added

---

app/server/controller/handler/chart.go
app/server/controller/handler/handlers.go
app/server/main.go
app/server/pkg/community/analytics.go
app/server/pkg/community/github/analytics.go
app/server/pkg/community/google/analytics.go
app/server/routes/routes.go

Signed-off-by: gdsoumya <gdsoumya@gmail.com>

Added Community Analytics Endpoint

---

app/server/pkg/analytics/analytics.go
app/server/pkg/community/google/analytics.go

Added separate analytics data of Chaos Operator installs and Experiment runs for time series graph.
Signed-off-by: gdsoumya <gdsoumya@gmail.com>

Updated Analytics for Community

---

.betterci/config.json
ci-docker-compose.yml

BetterCI setup for on-demand PR preview

Added BetterCi

---

app/server/pkg/community/google/analytics.go

What this PR does / why we need it:
Community API Update for litmus-portal.
Adds month of year wise data with formatted end-dates.

Backend Changes (Community API Update for litmus-portal).

---

.betterci/config.json
.travis.yml
Dockerfile.server
app/client/cypress.json
app/client/cypress/fixtures/example.json
app/client/cypress/integration/CharthubSmallTests.spec.js
app/client/cypress/plugins/index.js
app/client/cypress/support/commands.js
app/client/cypress/support/index.js
app/client/package-lock.json
app/client/package.json
app/client/src/components/BackButton/index.tsx
app/client/src/components/Footer/index.tsx
app/client/src/components/SearchBar/index.tsx
app/server/controller/handler/chart.go
app/server/controller/handler/handlers.go
app/server/main.go
app/server/pkg/analytics/analytics.go
app/server/pkg/community/analytics.go
app/server/pkg/community/github/analytics.go
app/server/pkg/community/google/analytics.go
app/server/routes/routes.go
ci-docker-compose.yml

Cherry Pick commits from staging to master
Commits taken :
- 6e083715a4a665d5f3f96a9c7604775bf8edbd2b
- 7db1288732cbd4ff4d5fca2dfb920b2be2460845
- 6ee0576d5f22cd2b8eead85462acac169968fbc4
- 23b6180026be3ae4ffa972fd354ef69e7885a476
- 23b6180026be3ae4ffa972fd354ef69e7885a476
- 0c5a422578304df0b22f4a2ae85a2e6b77e7d9e9
- c1f7cde3bf808d96a6a3187ada424d9bda0b1d72
- 29ee6fabcf1d6609262a99fe0c617f528d410f34

Cherry pick  commits from staging to master

---

app/client/src/components/Footer/index.tsx
app/client/src/hoc/withSidebar/index.tsx
app/client/src/hoc/withSidebar/styles.ts

Removed truncation for Operator Installs and added Github Star button

---

app/client/cypress/integration/CharthubSmallTests.spec.js

Signed-off-by: Jonsy13 <vedant.shrotria@mayadata.io>
- **Fixed the test for checking the footer links.**
Fixes: #211

Fixed the tests for clicking the Footer links

---

app/client/package-lock.json
app/client/src/components/Footer/index.tsx

Signed-off-by: ishangupta-ds <ishan.gupta@mayadata.io>
**What this PR does / why we need it:**
updating experiment runs representation.
**Which issue this PR fixes:**
fixes #217

updated experiment runs representation.

---

app/client/src/components/Footer/index.tsx

Footer Fix

---

app/client/src/components/UsefulLinks/index.tsx
app/client/src/pages/HomePage/index.tsx
app/client/src/pages/HomePage/styles.ts

Updated Header Description

---

app/client/src/pages/HomePage/styles.ts

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>

Minor CSS fixes

---

.github/CODEOWNERS
app/client/public/index.html

Added CODEOWNERS and Fixed twitter card

---

app/client/public/index.html

Fixed Font

---

.github/CODEOWNERS
app/client/public/index.html

- d6df99cdd891dd5d67b90258ccfaada1b30198e9 
- 9a436225e32ac74712b69fde8573ff7d6dc7c124

Cherrypick Fixes

---

app/client/src/components/Footer/index.tsx

Added Copyright for The Linux Foundation

---

app/client/src/components/Footer/index.tsx

Picked Commits :
- 35e380bc5f4fccaf032c24892a0c8d7161ac5c85

Added Copyright for The Linux Foundation (#238)

---

app/client/src/pages/ExperimentPage/index.tsx

Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- Resolved typo in the term "experiments"

resolve typo in charts experimentpage

---

app/client/src/components/InstallChaos/index.tsx
app/client/src/components/InstallChaos/styles.ts
app/client/src/pages/ExperimentPage/index.tsx
app/client/src/pages/ExperimentPage/styles.ts
app/client/src/pages/HomePage/styles.ts

Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>
- Updated the YAML link section
- Minor UI fixes

Updated the yaml link section and minor ui fixes

---

app/client/src/components/YamlEditor/Editor.tsx

Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**This PR will add Bug Fixes for Editor:--**
**- Find And Replace Functionality.**
**- Junk text on editing in last line.**

Added fix for find and Replace and Junk text on editing in last line.

---

app/client/src/components/InstallChaos/index.tsx
app/client/src/components/InstallChaos/styles.ts
app/client/src/components/YamlEditor/Editor.tsx
app/client/src/pages/ExperimentPage/index.tsx
app/client/src/pages/ExperimentPage/styles.ts
app/client/src/pages/HomePage/styles.ts

Cherry-Picking commits :
- fca0129c399b61d114623165128bcb69a97368b2
- efa0832758d03c6300256be66f5c80d96a9c5747

Cherry-pick commits from staging

---

app/client/public/index.html
app/client/src/components/Footer/index.tsx

Signed-off-by: ksatchit <karthik.s@mayadata.io>

(chore)org-update: update org name to chaosnative in resources

---

app/client/src/components/Header/index.tsx
app/client/src/components/YamlEditor/Editor.tsx

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

Display the latest 5 versions in header dropdown

---

app/client/src/components/DeveloperGuide/index.tsx
app/client/src/components/Footer/index.tsx
app/client/src/components/Header/index.tsx
app/client/src/pages/ExperimentPage/index.tsx

Signed-off-by: Sahil <sahil@chaosnative.com>

Updated broken links for litmus docs

---

app/server/pkg/analytics/analytics.go

Signed-off-by: ishangupta-ds <ishan@chaosnative.com>

Updating total events to unique events for removing duplicates from google analytics data

---

app/server/pkg/analytics/analytics.go

Signed-off-by: ishangupta-ds <ishan@chaosnative.com>

Adding total events for experiment runs for google analytics data

---

app/client/package-lock.json
app/client/package.json
app/client/public/robots.txt
app/client/public/sitemap.xml
app/client/src/robots-txt.config.js
app/client/src/sitemap-generator.js
app/client/src/sitemap-routes.js
app/server/pkg/analytics/analytics.go

cherry picking changes from staging for:
* [sitemap.xml](https://github.com/litmuschaos/charthub.litmuschaos.io/commit/5fe5ecdc9b646416404478831254a65ddb5a24f8) (SEO) 
* [robots.txt](https://github.com/litmuschaos/charthub.litmuschaos.io/commit/e6283bcce2cf69c945f71e7089b67efdf631b951) (SEO)
* [unique events for chaos operator installation count](https://github.com/litmuschaos/charthub.litmuschaos.io/commit/41438384b0f7a49dd10b8f3b4d3a50d7e2f9f860) (GA)
* [total events for chaos experiment run count](https://github.com/litmuschaos/charthub.litmuschaos.io/pull/282/commits/9a3a6d56528e4a21c90d853c5203ff57b7d7acaf) (GA)

cherry picking changes from staging for sitemap and unique events

---

Dockerfile.client
app/client/package-lock.json
app/client/package.json
app/client/src/redux/configureStore.tsx

Signed-off-by: Amit Kumar Das <amit@chaosnative.com>

package-update: Updated react-markdown package

---

.github/workflows/build.yml
app/server/pkg/analytics/analytics.go

Signed-off-by: Amit Kumar Das <amit.das@harness.io>

Added maxResult to fetch all analytics data

---

.github/workflows/build.yml
app/server/pkg/analytics/analytics.go

* Added maxResult to fetch all analytics data
* Updated build pipeline

Added maxResult to fetch all analytics data (#337)

---

app/client/src/components/ExperimentInfo/index.tsx
app/client/src/components/UsefulLinks/index.tsx
app/client/src/pages/ExperimentPage/index.tsx
app/client/src/redux/reducers/charts.ts

- Removed prerequisites and videos section
- Updated api fields

Removed prerequisites and videos section for 3.0.0 changes
